name: "master"

on:
  push:
    branches:
      - "master"

jobs:
  build-and-deploy:
    name: "Build and deploy"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@master"
      - uses: "actions/setup-node@master"
        with:
          node-version: "10.x"
      - uses: "chrislennon/action-aws-cli@1347f1d"
      - run: "npm install"
      - name: "Build the gatsby project"
        run: "npm run build"
      - name: "Deploy the build to s3"
        run: "aws s3 sync ./public s3://${AWS_S3_BUCKET} --delete"
        env:
          AWS_REGION: "us-east-1"
          AWS_S3_BUCKET: "${{ secrets.AWS_S3_BUCKET }}"
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
      - name: "Send CloudFront invalidation"
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${AWS_CLOUDFRONT_DISTRIBUTION_ID} \
            --paths "/*"
        env:
          AWS_CLOUDFRONT_DISTRIBUTION_ID: "${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }}"
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
